name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop ]

jobs:
  run-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      
      - name: Setup Node & Install dependencies
        shell: bash
        run: |
          cd server/
          npm install
      - name: run tests
        run: |
          npm test
